### ISSUE TITLE
Dependabot updates

### ISSUE THREAD

**Issue by amandamc** [adzerk/adzerk-api-specification#32]
Please merge and test the fixes to the alerts found in Secutiry - Dependabot. https://github.com/adzerk/adzerk-api-specification/security/dependabot
![Screen Shot 2022-09-09 at 2 56 06 PM](https://user-images.githubusercontent.com/5224328/189423989-4a07025f-60af-403b-b646-2a6259036fc5.png)

**Comment by vkurup** [comment]
Closed by #41
